### ISSUE TITLE
Saving metadata with Unicode characters results in database errors

### ISSUE THREAD

**Issue by brianhelba** [ImageMarkup/isic-archive#473]
This appears only in the final saving of metadata, not in the read-only validation.

This example came from an unstructured metadata field containing a Unicode value:
```
Traceback (most recent call last):
  File "/home/ubuntu/girder/girder/api/rest.py", line 567, in endpointDecorator
    val = fun(self, args, kwargs)
  File "/home/ubuntu/girder/girder/api/rest.py", line 1137, in POST
    return self.handleRoute(method, path, params)
  File "/home/ubuntu/girder/girder/api/rest.py", line 890, in handleRoute
    val = handler(**kwargs)
  File "/home/ubuntu/girder/girder/api/access.py", line 63, in wrapped
    return fun(*args, **kwargs)
  File "/home/ubuntu/girder/girder/api/rest.py", line 389, in wrapped
    return fun(*args, **kwargs)
  File "/home/ubuntu/girder/girder/api/rest.py", line 389, in wrapped
    return fun(*args, **kwargs)
  File "/home/ubuntu/girder/plugins/isic_archive/server/api/dataset.py", line 329, in applyMetadata
    dataset=dataset, metadataFile=metadataFile, save=save)
  File "/home/ubuntu/girder/plugins/isic_archive/server/models/dataset.py", line 405, in applyMetadata
    Image.save(image)
  File "/home/ubuntu/girder/girder/models/model_base.py", line 412, in save
    {'_id': document['_id']}, document, True)
  File "/home/ubuntu/girder/girder/external/mongodb_proxy.py", line 64, in __call__
    val = self.method(*args, **kwargs)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/pymongo/collection.py", line 849, in replace_one
    collation=collation)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/pymongo/collection.py", line 766, in _update
    codec_options=self.__write_response_codec_options).copy()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/pymongo/pool.py", line 482, in command
    self._raise_connection_failure(error)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/pymongo/pool.py", line 610, in _raise_connection_failure
    raise error
InvalidStringData: strings in documents must be valid UTF-8: 'Pigmented Spitz\x82s Nevus'
```

**Comment by msmolens** [comment]
@brianhelba Can you point me to a CSV file that demonstrates this issue?
