### ISSUE TITLE
Single image upload fails with a 500 when a multipart/form-data request is made

### ISSUE THREAD

**Issue by brianhelba** [ImageMarkup/isic-archive#540]
This should not result in unhandled exceptions, but should just cause the request to be gracefully rejected with a 400 error (ideally, with a descriptive error message).

**Comment by brianhelba** [comment]
An example stack trace from this:
```
ERROR: 500 Error
Traceback (most recent call last):
  File "/home/ubuntu/girder/girder/api/rest.py", line 593, in endpointDecorator
    val = fun(self, args, kwargs)
  File "/home/ubuntu/girder/girder/api/rest.py", line 1175, in POST
    return self.handleRoute(method, path, params)
  File "/home/ubuntu/girder/girder/api/rest.py", line 918, in handleRoute
    val = handler(**kwargs)
  File "/home/ubuntu/girder/girder/api/access.py", line 63, in wrapped
    return fun(*args, **kwargs)
  File "/home/ubuntu/girder/girder/api/rest.py", line 410, in wrapped
    return fun(*args, **kwargs)
  File "/home/ubuntu/girder/plugins/isic_archive/server/api/dataset.py", line 224, in addImage
    params = self._decodeParams(params)
  File "/home/ubuntu/girder/plugins/isic_archive/server/api/base.py", line 47, in _decodeParams
    decodedValue = json.loads(value)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
Additional info:
  Request URL: POST https://stage.isic-archive.com/api/v1/dataset/5aa63dab14773a2232d2dd61/image
  Query string: filename=test.jpg&signature=df
```
